import { Metadata } from "next";
import { CreateButton } from "./components";
import { ViewAllServices } from "./view-all-services";
export const metadata: Metadata = {
  title: "Services",
  description: "Generated by create next app",
};
export default function Services() {
  return (
    <div className="container mx-auto py-10">
      <h1 className="text-2xl font-bold mb-5">Quản lý dịch vụ</h1>
      <div className="mb-4">
        <CreateButton />
      </div>
      <ViewAllServices />
    </div>
  );
}
