import { Metadata } from "next";
import { CreateAccountAndCustomer, CreateUsageHistory } from "./components";

export const metadata: Metadata = {
  title: "Quick Create",
  description: "Generated by create next app",
};

export default function QuickCreate() {
    return (
      <div className="container flex justify-center items-center w-full h-full mx-auto py-10">
        <div className="flex justify-center items-center w-full space-x-10">
          <div className="flex flex-col justify-center items-center w-1/2">
            <h1 className="text-2xl font-bold mb-5">Tạo tài khoản</h1>
            <CreateAccountAndCustomer /> {/* Hiển thị form tạo tài khoản */}
          </div>
          <div className="flex flex-col justify-center items-center w-1/2">
            <h1 className="text-2xl font-bold mb-5">Tạo phiên sử dụng</h1>
            <CreateUsageHistory /> {/* Hiển thị form tạo phiên sử dụng */}
          </div>
        </div>
      </div>
    );
}
